// All test data for Experiment Overview tab
// Use this data to replace your existing TEST_DATA constant

export const TEST_DATA = [
  {
    id: 1,
    name: "Evaluating homepage content hierarchy modifications for April launch (P1)",
    startDate: "4/14/25",
    endDate: "4/21/25",
    stage: "Completed",
    platform: "Samsung.com",
    category: "BAU",
    lob: "Galaxy Phone, Galaxy Book, Galaxy Tab",
    country: "France",
    pageType: "Homepage",
    pageSection: "Hero Banner 2, Hero Banner 3, Promo Tile 1, Promo Tile 2",
    pageElement: "Promo Tile CTA, Hero Banner Image Link",
    product: "Galaxy Book Pro, Galaxy Book Air, Galaxy S18 Pro, Galaxy S18 Pro Max",
    hypothesis: "Moving Galaxy phones upward from hero sections to promotional tiles is expected to drive increased phone engagement while potentially reducing clicks on Galaxy Book and Tab products. Prioritizing Galaxy devices should encourage visitors to interact more with S18 series offerings. We anticipate this approach will generate higher relative downstream traffic and could yield approximately 35.1% improvement in add-to-bag activity.",
    result: "The increase in Galaxy Book progression rates occurred exclusively through promotional tiles. While Galaxy Book showed a 22.5% improvement, this was counterbalanced by Galaxy phone's -13% performance in the purchase funnel. Overall, the test registered a FLAT result at -5% versus control. Galaxy phone conversion showed slight negative movement compared to baseline, while Galaxy Tab flow demonstrated a +13% uptick. Based on these mixed signals, we're discontinuing Galaxy phone prioritization on homepage for conversion optimization."
  },
  {
    id: 2,
    name: "Measuring Welcome FP video removal effects on conversion metrics (Rome)",
    startDate: "1/21/25",
    endDate: "2/18/25",
    stage: "Completed",
    platform: "Samsung.com",
    category: "Rome",
    lob: "Galaxy Phone, Galaxy Watch",
    country: "United States",
    pageType: "Family Page",
    pageSection: "Welcome Moment, Consider Moment, Select Moment",
    pageElement: "Video Player, Skip Video CTA, Continue CTA",
    product: "Galaxy S18 Pro, Galaxy S14, Galaxy SE, Galaxy S14, Galaxy S15, Watch Ultra 2",
    hypothesis: "Removing the Welcome video is projected to accelerate user pathways to key information by reducing scroll depth requirements. This streamlined approach should enable faster access to product details while potentially simplifying the Galaxy Watch conversion journey through more direct navigation.",
    result: "The Welcome Video removal produced mixed results across product lines. For Galaxy phones, friction decreased notably with a 9% increase in Add-to-Bag rate and 4% growth in Flow rate. However, Galaxy Watch showed contrasting behavior with a -0.6% change in Phone Add to Buy rate after video removal. Testing Variation 4 (Welcome Cards removal) negatively impacted progression metrics for both Galaxy phones and Galaxy Watch across all measured dimensions, ultimately suggesting this approach reduced conversion effectiveness."
  },
  {
    id: 3,
    name: "Analyzing Welcome video elimination's effect on Family Page engagement (CN)",
    startDate: "3/10/25",
    endDate: "4/7/25",
    stage: "Completed",
    platform: "Samsung.com",
    category: "Rome",
    lob: "Galaxy Phone, Galaxy Watch",
    country: "China",
    pageType: "Family Page",
    pageSection: "Welcome Moment, Consider Moment, Select Moment",
    pageElement: "Welcome Video Player, Auto-play Toggle, Skip Button",
    product: "Galaxy S18 Pro, Galaxy S18 Pro, Galaxy SE 10, Watch Ultra",
    hypothesis: "Video removal from the Welcome experience aims to create more efficient information pathways, potentially increasing CTR and scroll engagement by streamlining the user journey.",
    result: "Results demonstrated varied performance patterns. Variation 3 (video removal) revealed that the Welcome Video actually reduced customer friction overall, generating a 6% improvement in Galaxy phone Add-to-Buy rate and 3% increase in Watch purchase progression. Variation 4 testing (Watch Ultra 2 prominence) significantly enhanced homepage engagement and product visibility, even among non-buyers. This positioning strategy elevated the entire product portfolio's perceived value. Specific Variation 4 metrics: +13.4% increase in Watch Family Page Visits, +14.2% growth in Any Watch Product Visits, +22.7% improvement in Watch See 1 Buy Flow Page, +13.8% boost in Any Watch See 1 Buy Flow Visits, +24.3% rise in Watch 1 Bag Adds."
  },
  {
    id: 4,
    name: "Testing Homepage and Watch Family hero banner product positioning strategy",
    startDate: "3/25/25",
    endDate: "4/14/25",
    stage: "Completed",
    platform: "Samsung.com",
    category: "BAU",
    lob: "Galaxy Watch",
    country: "Canada, Mexico, United States",
    pageType: "Homepage",
    pageSection: "Hero Banner 3",
    pageElement: "Learn More CTA, Product Browser Navigation",
    product: "Watch Series 10, Watch Ultra 2, Galaxy Watch",
    hypothesis: "By featuring a Galaxy Watch Family product browser within Homepage hero sections rather than separate product banners, we expect improved Watch LOR engagement and conversion rates. This consolidated approach should maximize hero banner real estate while showcasing the complete Watch portfolio more effectively.",
    result: "Emphasizing Watch Ultra 2 (Variation 4) delivered substantial Card Engagement improvements: +19.4% increase in Watch Family Page Visits, +14.2% growth in Any Watch Product Visits, +14.8% rise in Watch 1 Buy Flow Visits, +13.8% improvement in Any Watch See 1 Buy Flow Visits, +24.3% surge in Watch 1 Bag Adds. When testing DM campaign timing for Valentine's Day Launch and Last Chance messaging, early morning send times underperformed expectations. CTR and Conversion declined during early hours due to reduced customer purchase activity. However, when promoting the Galaxy S16a to price-conscious upgraders through DM, we observed increased conversion rates. This validated our hypothesis regarding pricing sensitivity among the upgrade segment."
  },
  {
    id: 5,
    name: "Examining DM campaign timing optimization for Valentine's Day (UK, DE)",
    startDate: "1/30/25",
    endDate: "2/7/25",
    stage: "Completed",
    platform: "DM",
    category: "BAU",
    lob: "Multi-OR",
    country: "United Kingdom, Germany",
    pageType: "DM",
    pageSection: "Email Body",
    pageElement: "Primary CTA Button, Shop Now Link",
    product: "Galaxy Phone, Galaxy Watch, Galaxy Buds",
    hypothesis: "Testing alternative send time strategies for Valentine's Day Launch and Last Chance Mile campaigns to determine optimal customer engagement windows. We hypothesize that adjusting from early morning sends will improve DM CTR and Conversion during peak purchase activity periods.",
    result: "Results validated timing matters significantly. Testing across multiple time zones revealed 10:00 AM UK (EST equivalent) generated optimal CTR and Conversion performance. These findings reinforce the value of strategic send time optimization, particularly avoiding early morning dispatches when customer purchase intent is lower."
  },
  {
    id: 6,
    name: "Optimizing Galaxy phone upgrader messaging in DM campaigns (FR, IT, ES)",
    startDate: "4/14/25",
    endDate: "4/24/25",
    stage: "Completed",
    platform: "DM",
    category: "BAU",
    lob: "Galaxy Phone",
    country: "France, Italy, Spain",
    pageType: "DM",
    pageSection: "Email Body, Product Card",
    pageElement: "Upgrade Now CTA, View Offers Link",
    product: "Galaxy S16a",
    hypothesis: "Featuring the Galaxy S16a model prominently in DM campaigns targeting price-sensitive upgrade customers should drive higher conversion and CTR. By emphasizing the more affordable option, we expect to resonate better with cost-conscious upgraders.",
    result: "Galaxy phone campaigns in France, Italy, and Spain showed improved results when highlighting the Galaxy S16a. The more accessible price point resonated particularly well with price-sensitive upgrade audiences, confirming our hypothesis about value-driven decision-making in this customer segment."
  },
  {
    id: 7,
    name: "Evaluating Galaxy S16e financing ribbon messaging impact in DM (Partnering Ribbon EU)",
    startDate: "2/28/25",
    endDate: "3/10/25",
    stage: "Completed",
    platform: "DM",
    category: "BAU",
    lob: "Galaxy Phone",
    country: "France, Germany",
    pageType: "DM",
    pageSection: "Email Header",
    pageElement: "Financing Ribbon Banner, Learn More CTA",
    product: "Galaxy S16a",
    hypothesis: "Implementing a 50% financing ribbon presentation (both with and without promotional discount) aims to enhance DM CTR and Conversion from households responsive to affordability messaging, ultimately improving Galaxy S16a purchase funnel entry.",
    result: "The EU 50% financing ribbon effectively communicated affordability regardless of CTA variation. Both messaging approaches successfully positioned the Galaxy S16a as more financially accessible, resulting in positive improvements in messaging effectiveness and customer engagement."
  },
  {
    id: 8,
    name: "Analyzing Galaxy for Students campaign page elements (FAQ and Comparison sections)",
    startDate: "1/30/25",
    endDate: "4/1/25",
    stage: "Completed",
    platform: "Samsung.com",
    category: "BAU",
    lob: "Galaxy Book",
    country: "Japan",
    pageType: "Galaxy For Student Landing Page",
    pageSection: "FAQ Section, Compare Section",
    pageElement: "FAQ Expand/Collapse Toggle, Compare Product CTA",
    product: "Galaxy Book Air 13\" and 15\", Galaxy Book Pro and 16\", Desktop options, Mini models, Studio models, Pro Display A2R",
    hypothesis: "By elevating the Education Store page prominence and enhancing critical capabilities on the Galaxy for Students landing page, we aim to create a more effective entry pathway to the edu store experience.",
    result: "The variation resulted in decreased click-through rates from the Galaxy for Students Page to the JP Education Store. Removing certain page elements also reduced overall engagement metrics in the JP Education Store, including standalone page interaction measures."
  },
  {
    id: 9,
    name: "Testing Homepage dynamic content strategy with Hero Banner and Promo Tile variations (P2)",
    startDate: "1/7/25",
    endDate: "1/20/25",
    stage: "Completed",
    platform: "Samsung.com",
    category: "BAU",
    lob: "Galaxy Phone, Galaxy Book, Galaxy Tab",
    country: "India, Japan",
    pageType: "Homepage",
    pageSection: "Hero Banner 1, Hero Banner 2, Hero Banner 3, Promo Tile 1, Promo Tile 2",
    pageElement: "Hero Banner Image Link, Promo Tile CTA, Learn More Button",
    product: "Galaxy S18, Galaxy Book 4, Galaxy Tab S9",
    hypothesis: "Examining how Hero Banner placement variations influence traffic patterns and conversion metrics across Galaxy Phone, Galaxy Book, and Galaxy Tab product lines.",
    result: "Homepage placement testing revealed mixed outcomes. Optimal content positioning doesn't always guarantee ideal conversion results. Specifically, neither generation number inclusion nor Pro model prioritization proved beneficial. Adding Generation Numbers produced a 2.1% decline in Galaxy Book product pageviews and 0.31% decrease in Buy Flow visitation. Leading with Pro Models caused a 1.4% reduction in Chapter flow CTR with no meaningful Buy Flow impact. Combining both approaches (Generation Numbers + Pro Model Priority) resulted in a 2.3% decline in Product Page visitation and 0.5% drop in Buy Flow Visits. These findings suggest neither strategy effectively improves customer engagement."
  },
  {
    id: 10,
    name: "Examining dynamic Galaxy Buds content ordering strategy (FP Ordering P1/02A/02+1/)",
    startDate: "1/21/25",
    endDate: "3/3/25",
    stage: "Completed",
    platform: "Samsung.com",
    category: "BAU",
    lob: "Galaxy Buds",
    country: "France, Germany, United Arab Emirates, United Kingdom, Thailand",
    pageType: "Family Page",
    pageSection: "Product Browse, Chapter Nav",
    pageElement: "Product Card CTA, Chapter Navigation Link, Learn More Button",
    product: "Galaxy Buds 4, Galaxy Buds Pro",
    hypothesis: "Testing product ordering within Global Nav to determine if prioritizing Galaxy Buds 4 and Galaxy Buds Pro in different sequences affects Family Page CTR and add-to-bag rates.",
    result: "Pro Model prioritization testing showed a 1.4% decline in Chapter flow CTR and 2.9% reduction in Buy Flow visitation, with negligible Buy Flow impact. Digital Mail campaigns featuring N- Model Priority demonstrated poor performance: -1.1% in Galaxy Phone N- Buy Flow Visitation Rate, -2.2% in Buy Flow CTR, -0.1% in add-to-bag rates, -0.1% decline in Buy Flow Visits, +3.5% increase in Add-to-Bag Rates. Generation Number incorporation led to 2.1% Galaxy Book decline and 0.31% Buy Flow visitation decrease. Overall, neither generation numbers nor Pro model leading strategies delivered beneficial results."
  },
  {
    id: 11,
    name: "Testing Galaxy Buds product ordering approach (FP Chapter Nav Product Ordering 02L/04/L/05)",
    startDate: "1/21/25",
    endDate: "3/3/25",
    stage: "Completed",
    platform: "Samsung.com",
    category: "BAU",
    lob: "Galaxy Buds",
    country: "France, United Arab Emirates, United Kingdom",
    pageType: "Family Page",
    pageSection: "Product Browse, Chapter Nav",
    pageElement: "Navigation Tab, Product Tile Click Area, Buy Now CTA",
    product: "Galaxy Buds 4, Galaxy Buds Pro",
    hypothesis: "Evaluating whether alternative product ordering sequences within Family Page Chapter Navigation impacts customer engagement and purchase funnel entry for Galaxy Buds products.",
    result: "Pro Model emphasis produced a 1.4% Chapter flow CTR decline, 2.9% Product Pagevisitation reduction, and 0.5% Buy Flow Visits decrease. Digital Mail N- Model positioning underperformed across metrics: -1.1% Galaxy Phone N- Buy Flow Visitation Rate, -2.2% Buy Flow CTR, -0.1% Buy Flow Visits decline, +3.5% Add-to-Bag Rates increase. Generation Number implementation caused 2.1% Galaxy Book decline and 0.31% Buy Flow visitation drop. Evidence consistently shows neither generation numbers nor Pro model prioritization strategies yield positive outcomes."
  },
  {
    id: 12,
    name: "Analyzing Galaxy Phone FP Select Moment content strategy (Select Moment: Galaxy N- Models - Liam Video + CTA Suppression 07K-P7L-OS)",
    startDate: "1/24/25",
    endDate: "3/7/25",
    stage: "Completed",
    platform: "Samsung.com",
    category: "Rome",
    lob: "Galaxy Phone",
    country: "France, Germany, United Kingdom",
    pageType: "Family Page",
    pageSection: "Select Moment",
    pageElement: "Product Image Link, Learn More CTA, Video Thumbnail",
    product: "Galaxy S15",
    hypothesis: "In Family Page Select Moment testing, we're evaluating whether directing customers to Type3 'Select Moment' experiences helps users identify optimal linking approaches. Focus is on measuring Galaxy N- Buy Flow Visitation Rate and CTA effectiveness.",
    result: "Testing on Samsung.com Homepage navigation to Galaxy Book Pro Product Page showed that Upgrade-Focused routing (versus FAQ section routing) resulted in lower engagement metrics. Upgrade messaging produced reduced performance compared to control: -2.9% in Buy Flow progression, -3.1% in Add-to-Bag rate, -2.2% in Buy Flow rate. Trade-In Page Visitation showed unusual behavior. These results contradict initial expectations about upgrade messaging effectiveness."
  },
  {
    id: 13,
    name: "Testing Galaxy Book Pro PP upgrade-focused messaging variations (Upgrade Page Customization 04)",
    startDate: "2/4/25",
    endDate: "3/5/25",
    stage: "Completed",
    platform: "Samsung.com",
    category: "BAU",
    lob: "Galaxy Book",
    country: "United States",
    pageType: "Product Page",
    pageSection: "Headline of 'Hero' Section: Why Upgrade",
    pageElement: "Trade-In Calculator Widget, Upgrade Now CTA, Compare Models Link",
    product: "Galaxy Book Pro",
    hypothesis: "For users navigating Samsung.com Homepage to Galaxy Book Pro Product Page, routing through Upgrade-Focused version (versus FAQ section path) should improve engagement through targeted messaging that addresses upgrade considerations. We expect this customization will increase engagement metrics and Buy Flow progression.",
    result: "Counter to expectations, Upgrade-Focused messaging underperformed the control group. Upgrade messaging generated lower engagement across key metrics: Trade-In Page Visitation rate showed unusual spike at +235%, while Buy Flow progression declined -2.9%, Add-to-Bag rate dropped -3.1%, and Buy Flow rate decreased -2.2%. These results suggest upgrade-specific messaging may not be the optimal approach for this customer segment."
  },
  {
    id: 14,
    name: "Exploring Galaxy Z Fold homepage hero placement strategy for holiday season",
    startDate: "11/25/25",
    endDate: null,
    stage: "Intake",
    platform: "Samsung.com",
    category: "BAU",
    lob: "Galaxy Z Fold",
    country: "United States, Canada",
    pageType: "Homepage",
    pageSection: "Hero Banner 1, Promo Tile 3",
    pageElement: "Hero Image Link, Shop Now CTA, Learn More Button",
    product: "Galaxy Z Fold 6, Galaxy Z Flip 6",
    hypothesis: "Positioning foldable devices prominently during the holiday shopping period may drive increased awareness and consideration among premium smartphone shoppers. We anticipate this visibility boost could improve engagement metrics and add-to-cart rates for the foldable product line.",
    result: ""
  },
  {
    id: 15,
    name: "Investigating Galaxy Tab product comparison tool effectiveness on Family Page",
    startDate: "11/20/25",
    endDate: null,
    stage: "Intake",
    platform: "Samsung.com",
    category: "BAU",
    lob: "Galaxy Tab",
    country: "United Kingdom, Germany, France",
    pageType: "Family Page",
    pageSection: "Compare Section, Product Selector",
    pageElement: "Compare Toggle Button, Specification Table, Add to Compare CTA",
    product: "Galaxy Tab S9, Galaxy Tab S9+, Galaxy Tab S9 Ultra",
    hypothesis: "Adding an interactive comparison tool allowing customers to view specifications side-by-side should reduce decision friction and accelerate the purchase journey. We expect this will improve conversion rates for customers evaluating multiple Tab models.",
    result: ""
  },
  {
    id: 16,
    name: "Testing Galaxy Watch trade-in messaging prominence on Product Detail Page",
    startDate: "12/5/25",
    endDate: "12/26/25",
    stage: "Proposal",
    platform: "Samsung.com",
    category: "Rome",
    lob: "Galaxy Watch",
    country: "United States",
    pageType: "Product Page",
    pageSection: "Trade-in Calculator Widget, CTA Section",
    pageElement: "Trade-In Value Display, Get Estimate CTA, Apply Trade-In Button",
    product: "Galaxy Watch 7, Galaxy Watch 7 Pro",
    hypothesis: "Elevating trade-in value messaging earlier in the product page experience (above the fold versus current mid-page placement) should increase trade-in program awareness. We hypothesize this will drive higher trade-in participation rates and overall conversion by reducing perceived purchase cost.",
    result: ""
  },
  {
    id: 17,
    name: "Analyzing Galaxy Book personalized recommendation engine on landing pages",
    startDate: "11/28/25",
    endDate: "12/19/25",
    stage: "Dev",
    platform: "Samsung.com",
    category: "BAU",
    lob: "Galaxy Book",
    country: "Japan, South Korea",
    pageType: "Landing Page",
    pageSection: "Personalized Product Recommendations Module",
    pageElement: "Recommended for You Section, Product Card CTA, View Details Link",
    product: "Galaxy Book 4, Galaxy Book 4 Pro, Galaxy Book 4 Ultra",
    hypothesis: "Implementing AI-driven product recommendations based on browsing behavior and device preferences should improve product discovery relevance. This personalized approach is expected to increase engagement with recommended products and boost overall Galaxy Book conversion rates.",
    result: ""
  },
  {
    id: 18,
    name: "Evaluating Galaxy S24 promotional banner effectiveness during Black Friday period",
    startDate: "11/15/25",
    endDate: "12/6/25",
    stage: "Live",
    platform: "Samsung.com",
    category: "BAU",
    lob: "Galaxy Phone",
    country: "United States, Canada, United Kingdom",
    pageType: "Homepage, Product Page",
    pageSection: "Promotional Banner, Discount Badge",
    pageElement: "Banner CTA, Countdown Timer, Shop Deals Button",
    product: "Galaxy S24, Galaxy S24+, Galaxy S24 Ultra",
    hypothesis: "Featuring time-limited Black Friday promotional banners with countdown timers and discount badges should create urgency and accelerate purchase decisions. We expect increased CTR on promotional elements and higher conversion rates during the promotional window.",
    result: ""
  },
  {
    id: 19,
    name: "Testing Galaxy Buds bundle offer presentation on checkout flow",
    startDate: "11/18/25",
    endDate: "12/9/25",
    stage: "Live",
    platform: "Samsung.com",
    category: "BAU",
    lob: "Galaxy Buds",
    country: "Germany, France, Italy, Spain",
    pageType: "Checkout Flow",
    pageSection: "Bundle Recommendation Module",
    pageElement: "Add Bundle CTA, Remove Item Link, Bundle Savings Badge",
    product: "Galaxy Buds 3, Galaxy Buds 3 Pro",
    hypothesis: "Introducing bundle offers (Galaxy Buds with Galaxy Phone purchase) at the checkout stage should increase average order value. By presenting relevant accessories with dynamic pricing, we anticipate improved attachment rates and revenue per transaction.",
    result: ""
  },
  {
    id: 20,
    name: "Analyzing mobile navigation menu structure optimization for Samsung.com",
    startDate: "11/12/25",
    endDate: "12/3/25",
    stage: "Live",
    platform: "Samsung.com",
    category: "Rome",
    lob: "Multi-Product",
    country: "Global",
    pageType: "Mobile Navigation",
    pageSection: "Hamburger Menu, Quick Access Icons",
    pageElement: "Menu Toggle Icon, Category Links, Search Bar",
    product: "All Products",
    hypothesis: "Restructuring mobile navigation to prioritize popular product categories and reduce menu depth should decrease bounce rates and improve mobile user experience. We expect faster product discovery and increased mobile conversion rates.",
    result: ""
  },
  {
    id: 21,
    name: "Measuring Galaxy ecosystem benefits messaging on cross-sell pages",
    startDate: "11/10/25",
    endDate: "12/1/25",
    stage: "Live",
    platform: "Samsung.com",
    category: "BAU",
    lob: "Multi-Product",
    country: "United States, United Kingdom",
    pageType: "Cross-sell Page",
    pageSection: "Ecosystem Benefits Section, Product Pairing Examples",
    pageElement: "Explore Ecosystem CTA, Add to Cart Button, Bundle Builder Link",
    product: "Galaxy Phone, Galaxy Watch, Galaxy Buds, Galaxy Tab",
    hypothesis: "Highlighting ecosystem integration benefits (seamless device connectivity, shared features) on cross-sell pages should increase multi-product purchase intent. We hypothesize this will improve cross-category conversion rates and increase customer lifetime value.",
    result: ""
  },
  {
    id: 22,
    name: "Examining Galaxy S24 financing options display hierarchy on Product Page",
    startDate: "10/28/25",
    endDate: "11/18/25",
    stage: "Result Analysis",
    platform: "Samsung.com",
    category: "BAU",
    lob: "Galaxy Phone",
    country: "United States",
    pageType: "Product Page",
    pageSection: "Financing Options Section, Payment Calculator",
    pageElement: "Calculate Payment CTA, Monthly Payment Display, Apply Now Button",
    product: "Galaxy S24, Galaxy S24+, Galaxy S24 Ultra",
    hypothesis: "Repositioning financing options higher on the product page (near price display versus current lower placement) should increase financing option awareness among price-sensitive customers. We expect this will improve financing program adoption rates and overall conversion by making premium devices more accessible.",
    result: ""
  },
  {
    id: 23,
    name: "Implementing optimized Galaxy Tab educational content layout on Family Page",
    startDate: "10/15/25",
    endDate: "11/5/25",
    stage: "Result Implementation",
    platform: "Samsung.com",
    category: "BAU",
    lob: "Galaxy Tab",
    country: "United States, Canada, Australia",
    pageType: "Family Page",
    pageSection: "Use Case Section, Feature Highlights",
    pageElement: "Explore Use Cases Link, Feature Demo Video, Compare Models CTA",
    product: "Galaxy Tab S9, Galaxy Tab S9 FE",
    hypothesis: "Restructuring educational content to feature use-case-driven narratives (productivity, creativity, entertainment) rather than technical specifications should better resonate with customer needs. Testing showed this approach improved engagement and conversion, now being implemented globally.",
    result: ""
  }
];
